services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: wpp_bot_api
    ports:
      - '5000:5000'
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SECRET_KEY=${SECRET_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_PRICE_ID=${STRIPE_PRICE_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - .:/app
      - ./chroma_data:/app/chroma_data